version: "3.9"

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    hostname: reverse-proxy
    tty: true
    stdin_open: true
    restart: "unless-stopped"

    volumes:
      - ./nginx/config.template:/etc/nginx/conf.d/default.conf

    ports:
      - 80:80
      - 443:443

    networks:
      - api-network

    links:
      - api

  api:
    container_name: api
    hostname: api
    tty: true
    stdin_open: true
    restart: "unless-stopped"

    build: .

    env_file:
      - .env

    networks:
      - api-network
      - cache-network

    links:
      - cache

  cache:
    image: redis
    container_name: cache
    hostname: cache
    tty: true
    stdin_open: true
    restart: "unless-stopped"

    networks:
      - cache-network

networks:
  api-network:
    driver: bridge

  cache-network:
    driver: bridge
